### ISSUE TITLE
Enhancement 1 - Prepare Index sheet with Summary and Hyperlink to each sheet

### ISSUE THREAD

**Issue by yogananda-muthaiah** [niro1987/SAP-Commissions-XML#2]
Hi Niels.

you can improve your spreadsheet with additional functionality like the count of each object and hyperlink for users to easily navigate each of the sheets for object name

Fixed Values - Count
Lookup table - Count
Rate Table - Count
Formulas - Count
Plans - Count
Plan Components - Count

**Comment by niro1987** [comment]
I've actually done that (although slightly differently) on a private version. I'll create a new branch for it so that you can have a look and get back to you.

**Comment by niro1987** [comment]
Hi @yogananda-muthaiah

Please have a look at #3
