### ISSUE TITLE
Error '91' 

### ISSUE THREAD

**Issue by leoneazevedo** [niro1987/SAP-Commissions-XML#4]
Hi! I am facing an issue when trying to parse an XML to Excel. It's throwing a specific error (Error 91) in the CREDITRULES.Parse_CreditRules subprocedure. Attached an example. This issue occurs with incentives subprocedures too. Some update about this repository? Thanks a lot. 

[DCR TLV UP RENT - REL.zip](https://github.com/niro1987/SAP-Commissions-XML/files/14117276/DCR.TLV.UP.RENT.-.REL.zip)

**Comment by niro1987** [comment]
Can you try it with the lasted version and report back please.

**Comment by niro1987** [comment]
@leoneazevedo please validate and close issue if fixed

**Comment by leoneazevedo** [comment]
Hi! Sorry for the delay, now it's working. Thank you

**Comment by leoneazevedo** [comment]
Hi Niro! I noticed that the lookup tables are not being filled 'correctly' or in the presented format. Do you have a new version for this purpose? Thank you.

**Comment by niro1987** [comment]
Can you raise a new issue explaining what you see and what you are expecting please.
